### ISSUE TITLE
Publishing the package?

### ISSUE THREAD

**Issue by kubo39** [lost22git/sieve_cache#3]
I don't intend to force you to do so, but it will be convenient for the users.

- https://nim-lang.github.io/nimble/create-packages.html#nimble-publish

**Comment by lost22git** [comment]
Thank you for your enthusiasm. This repo is currently at the level of self-entertainment. The implementation is quite rough and not enough for users to use.

**Comment by kubo39** [comment]
OK, feel free to close this issue.
